apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hanan-hpa
  namespace: prod-hanan
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-hanan
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
